[global]
dataFrameSerialization = "legacy"
developmentMode = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50
enableStaticServing = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#4facfe"
backgroundColor = "#f8f9ff"
secondaryBackgroundColor = "#ffffff"
textColor = "#2d3748"

[logger]
level = "error"meSerialization = "legacy"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#22c55e"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9ff"
textColor = "#2d3748"
font = "sans serif"
